# Generated by Django 2.2.2 on 2019-06-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
