# Generated by Django 2.2.2 on 2019-06-15 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_remove_userprofileinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete='CASCADE', related_name='comments', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='user', on_delete='DO_NOTHING', to=settings.AUTH_USER_MODEL),
        ),
    ]
