# Generated by Django 2.2.2 on 2019-06-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userprofileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
